default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tamirharris
  host: localhost
  # No password required

development:
  <<: *default
  database: course_udemy_development

test:
  <<: *default
  database: course_udemy_test

production:
  <<: *default
  database: course_udemy_production

